const nuevasVacantes=[
{tag:'ADMINISTRACIÓN',title:'Asistente Administrativo',location:'Zona 10, Guatemala',details:['Disponibilidad lunes a domingo y días festivos; domingo media jornada.','Dos días de descanso entre semana.','1-2 años en área administrativa, logística o afín; gestión de agenda, turnos e inventarios.','Excel intermedio y ERP deseable.','Graduada de Administración, Perito en Mercadotecnia o afín.'],offer:'Q4,000 + KPI Q800 promedio · total aprox. Q4,800 · prestaciones de ley'},
{tag:'MECÁNICA',title:'Mecánico General Diésel y Gasolina',location:'Amatitlán, Guatemala',details:['3-5 años en mantenimiento preventivo y correctivo de tren delantero, suspensión y transmisión.','Servicio menor y mayor de vehículos gasolina y diésel; diagnóstico de fallas.','Licencia A/B · 21-45 años.','Recién egresados de mecánica automotriz de INTECAP, Kinal o Fischmann pueden aplicar.','Horario lunes a viernes 8:00-17:00 y sábado medio día.'],offer:'Sueldo base + KPI promedio mensual Q8,000 · prestaciones de ley · crecimiento'},
{tag:'MECÁNICA INDUSTRIAL',title:'Mecánico de Motores Diésel/Gasolina Estacionarios',location:'Zona 3 Quetzaltenango / Amatitlán',details:['Con o sin experiencia; título de mecánico automotriz o industrial.','Diagnóstico de motores estacionarios gasolina y diésel y conocimientos básicos de electricidad.','Atención técnica a clientes y explicación de instalación y mantenimiento preventivo.','Conocimiento de motores Honda, Kama o similares.','18-40 años · lunes a sábado 8:00-18:00.'],offer:'Salario negociable hasta Q5,000 + parqueo para moto · prestaciones · estabilidad'},
{tag:'BODEGA / PRODUCCIÓN',title:'Auxiliares de Bodega, Producción, Empaque y Reparto',location:'Mixco y Ciudad de Guatemala',details:['Con o sin experiencia.','Buena condición física, responsabilidad, puntualidad y actitud de servicio.','Trabajo en equipo, dinamismo y disposición para aprender.'],offer:'Salario competitivo según perfil · prestaciones de ley · estabilidad · crecimiento'},
{tag:'VENTAS B2B',title:'Asesor Comercial B2B / Ejecutivo de Ventas',location:'Villa Nueva, Zona 12',details:['1-2 años en ventas B2B, idealmente materiales o servicios.','Relaciones interpersonales, propuestas y seguimiento de cartera.','Estudiante universitario ideal; conocimiento de procesos químicos ideal.','Licencia C/B y carro propio · 20-45 años.','Lunes a viernes 8:00-17:30.'],offer:'Q5,000 + 7% comisiones + depreciación + combustible + seguro · teléfono corporativo · viáticos'},
{tag:'INGENIERÍA / TÉCNICO',title:'Ingeniero Técnico Químico · Filtros Industriales',location:'Villa Nueva, Zona 12',details:['1-2 años en servicio al cliente, área técnica ideal.','Estudiante de Ingeniería Química o afín con fuertes conocimientos en procesos químicos.','PLC Allen Bradley y AutoCAD deseables.','Experiencia en purificación de agua para alimentos y bebidas deseable.','Licencia C/B y carro propio · 18-40 años.'],offer:'Q5,000 + 7% comisiones + depreciación + combustible + seguro · viáticos Centroamérica'},
{tag:'TÉCNICO INDUSTRIAL',title:'Técnico Electrónico / Electricista / Electromecánico / Mecánico Industrial',location:'Monte María 1, Zona 12, Villa Nueva',details:['Instalación de filtros para purificación de agua industrial y restaurantes.','Instrumentación, lectura de planos y montaje de tubería PVC y galvanizada.','Licencia C y formación técnica en electrónica, electromecánica, electricidad o afín ideal.','Responsable, dinámico y con deseos de aprender.','Lunes a viernes 8:00-17:30.'],offer:'Q4,252.28 + bonificaciones KPI después del período de prueba · prestaciones · crecimiento'},
{tag:'CONTABILIDAD',title:'Contador(a) Público y Auditor',location:'Villa Nueva, Zona 12, Monte María 1',details:['1 año de experiencia en área contable; ciclo contable y reportería financiera.','2-3 años en puestos similares.','Perito contador y 3er año de CPA/Administración.','Conocimientos sólidos de legislación tributaria y SAT.'],offer:'Salario negociable según experiencia · prestaciones de ley'},
{tag:'CONTABILIDAD',title:'Auxiliar Contable con Excel Intermedio',location:'Zona 2, Mixco',details:['Recién graduado Perito Contador con altos conocimientos contables.','Digitación indispensable y Excel intermedio.','Enfoque de crecimiento en habilidades técnicas y blandas.','18-35 años · lunes a jueves 8:00-17:00, viernes 8:00-16:00 y sábado eventual medio día.'],offer:'Q4,252.28 · prestaciones · estabilidad · oportunidad de crecimiento'},
{tag:'VENTAS / CAJA',title:'Cajero · Encargado de Tienda · Vendedor de Sala',location:'Zonas 7 y 10, Guatemala',details:['1-2 años en atención al cliente, persuasión, negociación y cierre.','Apertura/cierre de caja, cobros en efectivo y POS.','Control de inventarios; SAP deseable.','25-40 años.','Zona 10: lunes-viernes 7:00-18:00 y sábado 7:00-15:00. Zona 7: lunes-viernes 9:00-18:00 y sábado 9:00-17:00.'],offer:'Q4,300 + comisiones · promedio Q4,500-Q5,500 · 1% sobre ventas · prestaciones'}
];
function renderNuevasVacantes(){const list=document.getElementById('vacancyList');if(!list)return;nuevasVacantes.forEach(v=>{const card=document.createElement('article');card.className='vacancy-card';card.innerHTML=`<span class="tag">${v.tag}</span><h3>${v.title}</h3><p>📍 ${v.location}</p><ul>${v.details.map(x=>`<li>${x}</li>`).join('')}</ul><strong>💰 ${v.offer}</strong><a href="https://tally.so/r/mOzzok" target="_blank" rel="noopener" class="btn primary apply">Aplicar a esta plaza →</a>`;list.appendChild(card);});}
renderNuevasVacantes();